### PR TITLE
Use a modal in the Composer if the fields can't fit

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
If somebody is able to have a look at this and try to break it, you're welcome.

This should fix the issues regarding editing on mobile and small screen.

I also still want to try to add a way to force an increased default height for desktop.

image

image

image

image

### CODE REVIEW

**Comment by ghost** [comment]
Imo, I feel like this should be set no matter what length the fields are, I think it looks cleaner this way. I am going to test it, and I will let you know if I can break it ;)

**Comment by ghost** [comment]
Ok, it breaks it. I tried posting, and now, whenever I browse to my forum, I get the following error:
```
Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\vendor\flarum\core\src\Core\Post\RegisteredTypesScope.php on line 52

Fatal error: Uncaught RuntimeException: Output has been emitted previously; cannot emit response in C:\xampp\htdocs\vendor\zendframework\zend-diactoros\src\Response\SapiEmitterTrait.php:31 Stack trace: #0 C:\xampp\htdocs\vendor\zendframework\zend-diactoros\src\Response\SapiEmitter.php(27): Zend\Diactoros\Response\SapiEmitter->assertNoPreviousOutput() #1 C:\xampp\htdocs\vendor\zendframework\zend-diactoros\src\Server.php(162): Zend\Diactoros\Response\SapiEmitter->emit(Object(Zend\Diactoros\Response)) #2 C:\xampp\htdocs\vendor\flarum\core\src\Http\AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler)) #3 C:\xampp\htdocs\index.php(16): Flarum\Http\AbstractServer->listen() #4 {main} thrown in C:\xampp\htdocs\vendor\zendframework\zend-diactoros\src\Response\SapiEmitterTrait.php on line 31
```

**Comment by clarkwinkelmann** [comment]
@PartialDevAdmin I think that error usually pops up when you try using Flarum with PHP7.2, which is not supported with beta7. I don't think it's an error related to the extension or PR.

Could you try with another PHP version ? And if you were using a supported version,could you post the output of `php flarum info` ?

That's definitely not something I'm encountering when running this PR...

**Comment by poVoq** [comment]
Any chance you could release this as a dev/testing version on composer? I am happy to test it, but getting it to run manually will take some time given my current time constraints. Sorry for that.

**Comment by luceos** [comment]
@poVoq set the constraint of the extension in your composer.json to `dev-mobile-fields` then run composer update.

**Comment by poVoq** [comment]
Seems to work fine on php7.1 with the latest version of Flarum Beta7.

There are two remaining problems I see, first this is how the selection looks with Firefox mobile (it seems to work with the Flarum webview/chrome app though):
flarum1

Furthermore (but might be unrelated), if I enable also the "Polls" and "Byobu" apps it still brakes the mobile layout a bit.

**Comment by zkvlt** [comment]
Just tested this with some modifications on Flarum Beta 11 and seems to be working except that with >1 fields, it only manages to update the last field. 

Any ideas how/where to fix this? @clarkwinkelmann

**Comment by clarkwinkelmann** [comment]
@1zaak sorry I didn't reply earlier. I have not been able to test myself yet to see if I can reproduce. Just based on your description, I have no idea what it could be :grimacing:

I'd need to re-test the PR at some point, but it's on low priority right now...

**Comment by clarkwinkelmann** [comment]
With https://github.com/clarkwinkelmann/flarum-ext-composer-page now being available and compatible, I think it's time to finally close this old PR. From my tests the page is a much better solution in all regards, particularly when it comes to mobile experience.

**Pull request closed without merging**
